services:
    _defaults:
        autoconfigure: true
        autowire: true

    numero2\CEPackagistInfoBundle\Cron\Updater:
        arguments:
            - '@contao.framework'
        tags:
            - { name: contao.cronjob, interval: 'daily' }
